build:
  image: latest

version: 0.0.1

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  pip_install: true
#  install:
#    - requirements: docs/requirements.txt
#      extra_requirements:
#        - docs
 
 